# Generated by Django 6.0.3 on 2026-03-20 10:16

import django.core.validators
import django.db.models.deletion
import skillapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('academic_records', 'Academic Records'), ('academic_achievements', 'Academic Achievements'), ('professional_awards', 'Professional Awards'), ('competition_awards', 'Competition Awards'), ('certifications', 'Certifications'), ('internship_documents', 'Internship Documents'), ('identity_documents', 'Identity Documents'), ('professional_certifications', 'Professional Certifications'), ('technical_certifications', 'Technical Certifications'), ('government_legal', 'Government/Legal Certificates'), ('projects', 'Projects'), ('language_certificates', 'Language Certificates'), ('address_proofs', 'Address Proofs'), ('business_documents', 'Business Documents'), ('project_documents', 'Project Documents'), ('recommendation_letters', 'Recommendation Letters'), ('employment_documents', 'Employment Documents'), ('health_certificates', 'Health Certificates'), ('property_documents', 'Property Documents'), ('resumes', 'Resumes'), ('photo_documents', 'Photo Documents'), ('other', 'Other')], default='other', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(choices=[('important', 'Important'), ('official', 'Official'), ('personal', 'Personal'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('archived', 'Archived')], default='active', max_length=10)),
                ('file', models.FileField(upload_to=skillapp.models.document_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip'])])),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skillshelf_document',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
