# Generated by Django 6.0.3 on 2026-03-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0004_document_expiry_date_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doc_passcode',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
