# Generated by Django 6.0.3 on 2026-03-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0005_user_doc_passcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passkey_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_preference',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('none', 'None')], default='email', max_length=10),
        ),
    ]
